parameters:
#    training_battery.example.class: Training\Bundle\BatteryBundle\Example

services:
#    training_battery.example:
#        class: %training_battery.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
